# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ incpatch .Version }}-next"

gomod:
  proxy: true

report_sizes: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

builds:
  - env:
      - CGO_ENABLED=0
      - HOME={{ .Env.HOME }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format: tar.gz
    files:
      - data/**
      - LICENSE
      - README.md

signs:
  - artifacts: checksum

nfpms:
  - id: default
    package_name: randonamer
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://pietrobondioli.com.br
    maintainer: Pietro Bondioli <email@pietrobondioli.com.br
    description: |-
      A coolname generator with support to many languages and possibility to use custom configuration files.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    dependencies:
      - git
    provides:
      - randonamer
    replaces:
      - randonamer
    bindir: /usr/bin
    contents:
      - src: ./data/config-linux.yaml
        dst: "{{ .Env.HOME }}/.config/{{ .ProjectName }}/config.yaml"
        file_info:
          mode: 0644
      - src: ./data/en/
        dst: "{{ .Env.HOME }}/.config/{{ .ProjectName }}/data/en/"
        type: tree
        file_info:
          mode: 0644
      - src: ./data/pt_br/
        dst: "{{ .Env.HOME }}/.config/{{ .ProjectName }}/data/pt_br/"
        type: tree
        file_info:
          mode: 0644

aurs:
  - homepage: https://github.com/pietrobondioli/randonamer
    description: "A coolname generator with support to many languages and possibility to use custom configuration files."
    maintainers:
      - "Pietro Bondioli <email@pietrobondioli.com.br>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/randonamer-bin.git"
    package: |-
      # bin
      install -Dm755 "./randonamer" "${pkgdir}/usr/bin/randonamer"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/randonamer/LICENSE"

      # config and data
      install -Dm644 "./data/config-linux.yaml" "${pkgdir}${HOME}/.config/randonamer/config.yaml"
      install -d "${pkgdir}${HOME}/.config/randonamer/data/en"
      install -Dm644 "./data/en/*" "${pkgdir}${HOME}/.config/randonamer/data/en/"
      install -d "${pkgdir}${HOME}/.config/randonamer/data/pt_br"
      install -Dm644 "./data/pt_br/*" "${pkgdir}${HOME}/.config/randonamer/data/pt_br/"

nix:
  - name: randonamer
    repository:
      owner: pietrobondioli
      name: randonamer
    homepage: https://github.com/pietrobondioli/randonamer
    description: "A coolname generator with support to many languages and possibility to use custom configuration files."
    path: pkgs/randonamer/default.nix
    license: MIT

winget:
  - name: randonamer
    publisher: randonamer
    license: MIT
    homepage: https://github.com/pietrobondioli/randonamer
    short_description: "A coolname generator with support to many languages and possibility to use custom configuration files."
    repository:
      owner: randonamer
      name: winget-pkgs
      branch: "randonamer-{{.Version}}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

scoops:
  - repository:
      owner: randonamer
      name: scoop-bucket
    directory: bucket
    homepage: https://github.com/pietrobondioli/randonamer
    description: "A coolname generator with support to many languages and possibility to use custom configuration files."
    license: MIT
